# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-02T13:32:52Z"
  labels:
    app: push-notification
  name: push-notification
spec:
  containers:
  - args:
    - -p
    - 8080:8080
    command:
    - /docker-gs-ping
    env:
    - name: PATH
      value: /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: GOPATH
      value: /go
    - name: GOLANG_VERSION
      value: 1.16.9
    image: localhost/pushnotification:latest
    name: pushnotification
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  dnsConfig: {}
  restartPolicy: Always
status: {}

